services:

  apisvc-prod:
    container_name: apisvc-prod
    image: pbranestrategy/tac-case-api-service:0.1.3
    environment:
      - SERVER_PORT=8080
      - AUTH_SVC_ISSUER_URI=http://authsvr-prod:8080/oauth2/jwks
      - API_SVR_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - production

  apisvc-dev:
    container_name: apisvc-dev
    image: pbranestrategy/tac-case-api-service:0.1.3
    environment:
      - SERVER_PORT=8080
      - AUTH_SVC_ISSUER_URI=http://authsvr-dev:8080/oauth2/jwks
      - API_SVR_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    profiles:
      - development

networks:
  backend:
    driver: bridge

volumes:
  authdb_data:

