services:
  apisvc-prod-mono:
    container_name: apisvc-prod-mono
    image: pbranestrategy/tac-case-api-service-mono:0.2.0
    environment:
      - API_SVC_ENV=production
      - API_SVR_MAX_FILE_SIZE_MB=20
      - AUTH_SVR_ENV=production
      - AUTH_SVR_REPO=inMemory
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - ACCESS_TOKEN_EXPIRATION_MIN=5
      - SERVER_PORT=8080
      - API_SVC_MODE=Freshdesk
      - FD_API_KEY=0123456789ABCDEFGHI
      - FD_BASE_URI=https://domain.freshdesk.com/api/v2
      - FD_CUSTOMER_NAME=Beacon
      - FD_TAC_CASE_ID_PREFIX="_2-"
      - FD_RMA_CASE_ID_PREFIX="_3-"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    #    restart: unless-stopped
    profiles:
      - production

  apisvc-dev-mono:
    container_name: apisvc-dev-mono
    image: pbranestrategy/tac-case-api-service-mono:0.2.0
    environment:
      - API_SVC_ENV=development
      - AUTH_SVR_ENV=development
      - AUTH_SVR_REPO=inMemory
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - ACCESS_TOKEN_EXPIRATION_MIN=5
      - SERVER_PORT=8080
      - API_SVC_MODE=Database
      - FD_API_KEY=0123456789ABCDEFGHI
      - FD_BASE_URI=https://domain.freshdesk.com/api/v2
      - FD_CUSTOMER_NAME=Beacon
      - FD_TAC_CASE_ID_PREFIX="_2-"
      - FD_RMA_CASE_ID_PREFIX="_3-"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    #    restart: unless-stopped
    profiles:
      - development

  client-prod:
    container_name: client-prod-mono
    environment:
      - TAC_API_HOST=apisvc-prod-mono
      - TAC_API_HOST_PORT=8080
      - TAC_AUTH_HOST=apisvc-prod-mono
      - TAC_AUTH_HOST_PORT=8080
      - AUTH_BASE_URI=http://apisvc-prod-mono:8080
      - RESOURCE_BASE_URI=http://apisvc-prod-mono:8080/api/v1
      - TOKEN_EP_URI=/oauth2/token
      - AUTH_EP_URI=/oauth2/authorize
      - USER_INFO_EP_URI=/oauth2/userinfo
      - JWK_SET_EP_URI=/oauth2/jwks
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - CLIENT_SCOPE=read.cases,write.cases
      - CLIENT_CONN_TIMEOUT=2000
      - CLIENT_RESP_TIMEOUT=3000
    image: pbranestrategy/tac-case-api-oauth2-sample-client:0.1.7
    tty: true
    stdin_open: true
    networks:
      - backend
    profiles:
      - production

  client-dev:
    container_name: client-dev
    image: pbranestrategy/tac-case-api-oauth2-sample-client:0.1.7
    environment:
      - TAC_API_HOST=apisvc-dev-mono
      - TAC_API_HOST_PORT=8080
      - TAC_AUTH_HOST=apisvc-dev-mono
      - TAC_AUTH_HOST_PORT=8080
      - AUTH_BASE_URI=http://apisvc-dev-mono:8080
      - RESOURCE_BASE_URI=http://apisvc-dev-mono:8080/api/v1
      - TOKEN_EP_URI=/oauth2/token
      - AUTH_EP_URI=/oauth2/authorize
      - USER_INFO_EP_URI=/oauth2/userinfo
      - JWK_SET_EP_URI=/oauth2/jwks
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - CLIENT_SCOPE=read.cases,write.cases
      - CLIENT_CONN_TIMEOUT=2000
      - CLIENT_RESP_TIMEOUT=3000
    tty: true
    stdin_open: true
    networks:
      - backend
    profiles:
      - development

networks:
  backend:
    driver: bridge
