version: '3.8'

services:
  api-server:
    container_name: tac-case-api-server-prod
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      SERVER_PORT: 8080
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://localhost:9080/auth-server
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://localhost:9080/oauth2/jwks
    ports:
      - "8080:8080"
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - production

  api-server-dev:
    container_name: tac-case-api-server-dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      - SERVER_PORT=8080
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI="http://localhost:9081/auth-server"
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI="http://localhost:9081/oauth2/jwks"
    ports:
      - "8081:8080"
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - development

networks:
  backend:
    driver: bridge

#volumes:
#  authdb_data:

