version: '3.8'

services:
  api-server:
    container_name: tac-case-api-server-prod
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      SERVER_PORT: 8080  # Explicitly set the server's listening port
    ports:
      - "8081:8080"
#    networks:
#      - backend
#    restart: unless-stopped
    profiles:
      - production

  api-server-dev:
    container_name: tac-case-api-server-dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      SERVER_PORT: 8080  # Explicitly set the server's listening port
    ports:
      - "8082:8080"  # Different port for dev to avoid conflicts
#    networks:
#      - backend
#    restart: unless-stopped
    profiles:
      - development

networks:
  backend:
    driver: bridge

#volumes:
#  authdb_data:

