version: '3.8'

services:

  apisvc-prod:
    container_name: tac-case-api-svc
    image: tac-case-api-svc
    env_file: 
      - path: ./apisvc-prod.env
        required: true
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - production

  apisvc-dev:
    container_name: tac-case-api-svc
    image: tac-case-api-svc
    env_file: 
      - path: ./apisvc-dev.env
        required: true
    build:
      context: ./tac-case-api-service
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    profiles:
      - development

networks:
  backend:
    driver: bridge
